### ISSUE TITLE
Incomming call

### ISSUE THREAD

**Issue by emilianovilas** [javray/SIP#1]
Hola, cómo estás Javier?
Escribo esto posiblemente porque no entiendo cómo es el flujo de funcionamiento del plugin, pero no consigo un buen funcionamiento para las llamadas entrantes. Desde la interfaz javascript tengo que llamar a incomingCall cuando me llega una llamada y luego answerCall para atenderla. Según me imagino yo el funcionamiento, incomingCall debería dispararse automáticamente cuando una llamada entra.
Entonces, hay algo que funciona mal o soy yo que entiendo mal el flujo?
Saludos!

**Comment by emilianovilas** [comment]
I kept following the code and noticed the incommingCall event... So my question is answered. Incoming should be spelled with only one "m" though. It's a minor thing.
Cheers and congratulation on a great plugin!

**Comment by javray** [comment]
Fixed
